apiVersion: v1
kind: Service
metadata:
  name: kylin-svc
  namespace: kylin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 7070
  - name: https
    port: 443
    targetPort: 7443
  selector:
    app: kylin
    query: "true"
  type: LoadBalancer